name = "fcm-worker"
main = "src/index.ts"
compatibility_date = "2022-06-21"
node_compat = true 

kv_namespaces = [
  { binding = "IMAGES", id = "9b3ce91bd0d642b3a15066ff753473fk", preview_id = "9b3ce91bd0d642b3a15066ff753473fc" }
]